# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c1410d7006624ca5d5810b9922ed9c365fd26272e6a69fdc5a28910290144b443567041c0ed1eb50c8c4ae6bb78596794edd389868ec378e74ee6c97d19f36

test:
  secret_key_base: c2fbd7ad728a92f5c5ecd6dd1a9e7bbcf34aa7c0a3ef37a40e1b3e64033c50c74a506126511ab9e5eae0f0472451f89121a42d3d4c8a530b9986455cf1bbf865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
